name: Set up Test JDK
description: Sets up the JDK required to run platform-tooling-support-tests
inputs:
  distribution:
    required: true
    description: 'The JDK distribution to use'
    default: 'liberica'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: 8
        check-latest: true
    - shell: bash
      run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
    - uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: 17
        check-latest: true
    - shell: bash
      run: echo "JDK17=$JAVA_HOME" >> $GITHUB_ENV
